language: node_js

sudo: false

node_js:
  - "5"

cache:
  apt: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: github.com

script:
  - 'npm run build'
  - 'npm run clean'
  - 'npm run deploy  "${TRAVIS_PULL_REQUEST}"'

branches:
  only:
    - master

env:
  global:
    - CXX: g++-4.8
    - GH_REPO: "github.com/o2team/events.git"
    - secure: "Y+25rzy0w15XiFi+c1uzgf1iYdMykQHDxrvwLs/BAP6/1vKuAcPny+34OWXuIbCrzXd7v8XiHExegotS2V9KmTXxjxdUnLOC+ufkKdGy/2ZzEpBY0zdwM7o/pulXuJht6urr0XZLcMPe/BGdLAhvDQepfv6DYG7vImkaAwYPA3iTHq/w04BZuGGj+eR56tJOYtfPryDjBKPhhMQ1KpTCDQ/l6Vzl1HlmSUAL6FRJhnd8vJPx8xVokDPUNaTaOGtcZAZjkvQjA5POYF++XzDzvhZdxrVaizUVk4W1e066M1vk2iSJ9u+ftcR/vfEQ5IzB8UrJIfjqo2tkzVFsmixN8j0DTz8AyjIiKOj6BKMXBfPdo0ro1oCAlzup4QHHVh7mm0WyyT9FP7yhObXi1YQy/cS92TJV695907Puat4jx2w46QOM0RhsjPbiUZ6YlGrH/0YtaRBC7k6BoQ45rH/CIPuMLeiwPo4nZHNX/k0Is7HZi+i9Mjl5RjQK3U/NsVymKLNhhmFmiBao3ClbUaLwA8UqSK9BWjA2G7Cp89101zuakXIXK3zcw2cMzYmYEsM3ighLdXgfbsG0vMfEekGhhjk6rIvsxYPlB/vi/0k76PzzZK7xFKdTnHvtjj+pZwOYkfxYFjhCUh1HDvf+wDjEaW6xtKHdyYMQ7Aobatk3QqQ="
