logo:
    url: img/logo-square-120.png

post:
    cover: post-default.png
    img_dir: img/post/

layout:
    feature_count: 4

# baidu push
baidu_push: false

# dict daily
## http://dict.cn/foot/help2.htm
dict_daily: false

# daily words
daily_words: true 

# Content
fancybox: false

# Code Highlight theme
# Available value:
#    normal | night | eighties | blue | bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

# Wechat
wechat:
  desc: "海海人生，无折腾不为乐。"
